# the different stages of this Dockerfile are meant to be built into separate images
# https://docs.docker.com/compose/compose-file/#target

ARG PHP_VERSION=7.2
ARG DRUPAL_VERSION=8.6.7

#Build Stage
FROM php:${PHP_VERSION}-fpm-alpine AS builder

# persistent / runtime deps
RUN apk add --no-cache \
		acl \
		file \
		gettext \
		git \
		libpng-dev \
	;

ARG APCU_VERSION=5.1.16
RUN set -eux; \
	apk add --no-cache --virtual .build-deps \
		$PHPIZE_DEPS \
		icu-dev \
		libzip-dev \
		postgresql-dev \
		zlib-dev \
	; \
	\
	docker-php-ext-configure zip --with-libzip; \
	docker-php-ext-install -j$(nproc) \
		intl \
		pdo_pgsql \
		zip \
		gd \
	; \
	pecl install \
		apcu-${APCU_VERSION} \
	; \
	pecl clear-cache; \
	docker-php-ext-enable \
		apcu \
		opcache \
	; \
	\
	runDeps="$( \
		scanelf --needed --nobanner --format '%n#p' --recursive /usr/local/lib/php/extensions \
			| tr ',' '\n' \
			| sort -u \
			| awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
	)"; \
	apk add --no-cache --virtual .api-phpexts-rundeps $runDeps; \
	\
	apk del .build-deps

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

#Add project to builder stage
COPY . /app

WORKDIR /app

# https://getcomposer.org/doc/03-cli.md#composer-allow-superuser
ENV COMPOSER_ALLOW_SUPERUSER=1
RUN set -eux; \
    composer global require "hirak/prestissimo:^0.3" --prefer-dist --no-progress --no-suggest --classmap-authoritative; \
    composer clear-cache
ENV PATH="${PATH}:/root/.composer/vendor/bin"

RUN set -eux; \
	composer install --prefer-dist --no-dev --no-scripts --no-progress --no-suggest; \
	composer clear-cache

#Release Stage
FROM drupal:${DRUPAL_VERSION} as drupal

COPY --from=builder /app/web/modules /var/www/html/modules
COPY --from=builder /app/web/profiles /var/www/html/profiles
COPY --from=builder /app/web/themes /var/www/html/themes

#Copy patched core files
COPY --from=builder /app/patched/MonthDate.php /var/www/html/core/modules/views/src/Plugin/views/argument/MonthDate.php

#Allow environment variables
COPY --from=builder /app/web/sites/default/settings.environment.php /var/www/html/sites/default/
RUN cp /var/www/html/sites/default/default.settings.php /var/www/html/sites/default/settings.php \
    && chmod 0777 /var/www/html/sites/default/settings.php \
    && printf "if (file_exists(\$app_root . '/' . \$site_path . '/settings.environment.php')) { \n\
  include \$app_root . '/' . \$site_path . '/settings.environment.php'; \n\
}\n" >> /var/www/html/sites/default/settings.php
